name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build release assets

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set the release version (tag)
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set the release version (main)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV
    - name: Run build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: <%= moduleName %>.wasm
        path: ./build/js/packages/<%= moduleName %>-wasm/kotlin/<%= moduleName %>-wasm.wasm
